{{- if .variables.clusterAutoscalerEnabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.10.7
    helm:
      values: |
        autoDiscovery:
          tags: "kubernetes.io/cluster/{{ .name }}"
          clusterName: "{{ .name }}"
        extraArgs:
          v: 2
          stderrthreshold: error
          logtostderr: true
          write-status-configmap: true
          max-node-provision-time: 20m0s
          scan-interval: 30s
          scale-down-enabled: true
          scale-down-delay-after-add: 20m
          scale-down-utilization-threshold: 0.4
          max-graceful-termination-sec: 600
          skip-nodes-with-system-pods: true
          skip-nodes-with-local-storage: false
        serviceMonitor:
          enabled: false
          namespace: kube-system
          selector:
            release: cluster-autoscaler
        rbac:
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: {{ remoteState "this.iam_assumable_role_autoscaling_autoscaler.this_iam_role_arn" }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
{{- end }}
