apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "{{ remoteState "this.eks.worker_iam_role_arn" }}"
      "username": "system:node:{{ "{{EC2PrivateDNSName}}" }}"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
