name: dev
kind: Project
backend: aws-backend
variables:
  organization: my-company # sample global variable
  region: eu-central-1
  state_bucket_name: cdev-state # create and set your s3 bucket here
# exports:
  # AWS_PROFILE: my-profile
  # CDEV_TF_BINARY: /usr/local/bin/terraform-0.14.9 # optional set of TF version
